In [1]:
# Prevents me from having to reload kernel in VS Code, might not be needed to run in docker/anaconda
from IPython import get_ipython
ip = get_ipython()
ip.magic("reload_ext autoreload")  # these will enable module autoreloading
ip.magic("autoreload 2")

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from src import pre_process
from src import constants
from src import process

In [33]:
df = pre_process.getTrain()
df

ID  Loan Amount  Funded Amount  Funded Amount Investor  Term  \
0      65087372      10000.0        32236.0             12329.36286    59   
1       1450153       3609.0        11940.0             12191.99692    59   
2       1969101      28276.0         9311.0             21603.22455    59   
3       6651430      11170.0         6954.0             17877.15585    59   
4      14354669      16890.0        13226.0             13539.92667    59   
...         ...          ...            ...                     ...   ...   
67458  16164945      13601.0         6848.0             13175.28583    59   
67459  35182714       8323.0        11046.0             15637.46301    59   
67460  16435904      15897.0        32921.0             12329.45775    59   
67461   5300325      16567.0         4975.0             21353.68465    59   
67462  65443173      15353.0        29875.0             14207.44860    59   

      Batch Enrolled  Interest Rate Grade Sub Grade Employment Duration  ...  \
0         BAT2522922      11.135007     B        C4            MORTGAGE  ...   
1         BAT1586599      12.237563     C        D3                RENT  ...   
2         BAT2136391      12.545884     F        D4            MORTGAGE  ...   
3         BAT2428731      16.731201     C        C3            MORTGAGE  ...   
4         BAT5341619      15.008300     C        D4            MORTGAGE  ...   
...              ...            ...   ...       ...                 ...  ...   
67458     BAT3193689       9.408858     C        A4            MORTGAGE  ...   
67459     BAT1780517       9.972104     C        B3                RENT  ...   
67460     BAT1761981      19.650943     A        F3            MORTGAGE  ...   
67461     BAT2333412      13.169095     D        E3                 OWN  ...   
67462     BAT1930365      16.034631     B        D1            MORTGAGE  ...   

        Recoveries Collection Recovery Fee Collection 12 months Medical  \
0         2.498291                0.793724                            0   
1         2.377215                0.974821                            0   
2         4.316277                1.020075                            0   
3         0.107020                0.749971                            0   
4      1294.818751                0.368953                            0   
...            ...                     ...                          ...   
67458   564.614852                0.865230                            0   
67459     2.015494                1.403368                            0   
67460     5.673092                1.607093                            0   
67461     1.157454                0.207608                            0   
67462     1.856480                0.366386                            0   

      Application Type  Last week Pay  Accounts Delinquent  \
0           INDIVIDUAL             49                    0   
1           INDIVIDUAL            109                    0   
2           INDIVIDUAL             66                    0   
3           INDIVIDUAL             39                    0   
4           INDIVIDUAL             18                    0   
...                ...            ...                  ...   
67458       INDIVIDUAL             69                    0   
67459       INDIVIDUAL             14                    0   
67460       INDIVIDUAL            137                    0   
67461       INDIVIDUAL             73                    0   
67462       INDIVIDUAL             54                    0   

       Total Collection Amount  Total Current Balance  \
0                         31.0               311301.0   
1                         53.0               182610.0   
2                         34.0                89801.0   
3                         40.0                 9189.0   
4                        430.0               126029.0   
...                        ...                    ...   
67458                     48.0               181775.0   
67459                    

In [30]:
smoothed_df = pre_process.pre_process_data_smooth(df, 2)

No missing vlaues found


In [ ]:
pre_process.plot_data(smoothed_df, x_axis='Loan Status')

In [10]:
#pre_process.getParallelGraph(df.loc[df['Loan Status'] == False])

In [11]:
#pre_process.getParallelGraph(df.loc[df['Loan Status'] == True])

In [38]:
train, test = process.getTrainAndTestSet(df)
train_smoothed, test_smoothed = process.getTrainAndTestSet(smoothed_df)

In [35]:
process.testLogisticRegression(train, test)

Accuracy:  0.9084710590676647
[[12258     0]
 [ 1235     0]]


In [6]:
process.testRandomForest(train, test)

Accuracy:  1.0
[[12258     0]
 [    0  1235]]


In [39]:
process.testLogisticRegression(train_smoothed, test_smoothed)

Accuracy:  0.9084710590676647
[[12258     0]
 [ 1235     0]]


In [37]:
process.testRandomForest(train_smoothed, test_smoothed)

Accuracy:  1.0
[[12258     0]
 [    0  1235]]
