In [18]:
# Prevents me from having to reload kernel in VS Code, might not be needed to run in docker/anaconda
from IPython import get_ipython
ip = get_ipython()
ip.magic("reload_ext autoreload")  # these will enable module autoreloading
ip.magic("autoreload 2")

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from src import pre_process
from src import constants
from src import process

In [20]:
df = pre_process.getTrain()

In [21]:
smoothed_df = pre_process.pre_process_data_smooth(df, 2)
normalized_df = pre_process.normalize_data(df)

No missing vlaues found


In [ ]:
pre_process.plot_data(normalized_df, x_axis='Loan Status')

In [ ]:
#pre_process.getParallelGraph(df.loc[df['Loan Status'] == False])

In [ ]:
#pre_process.getParallelGraph(df.loc[df['Loan Status'] == True])

In [22]:
train, test = process.getTrainAndTestSet(df)
train_normalized, test_normalized = process.getTrainAndTestSet(normalized_df)
train_smoothed, test_smoothed = process.getTrainAndTestSet(smoothed_df)
train_smoothed_normalized, test_smoothed_normalized = process.getTrainAndTestSet(pre_process.normalize_data(smoothed_df))

In [ ]:
process.testLogisticRegression(train, test)

process.testLogisticRegression(train_normalized, test_normalized)

process.testLogisticRegression(train_smoothed, test_smoothed)

process.testLogisticRegression(train_smoothed_normalized, test_smoothed_normalized)

In [25]:
process.testKNeighborsClassifier(train, test)

process.testKNeighborsClassifier(train_normalized, test_normalized)

process.testKNeighborsClassifier(train_smoothed, test_smoothed) # Gives best accuracy and doubles f-score

process.testKNeighborsClassifier(train_smoothed_normalized, test_smoothed_normalized)

Accuracy:  0.9027643963536649
F1 Score:  0.012048192771084336
[[12173    75]
 [ 1237     8]]
Accuracy:  0.9006151337730676
F1 Score:  0.008869179600886918
[[12146    72]
 [ 1269     6]]
Accuracy:  0.9028385088564441
F1 Score:  0.019446522064323114
[[12169    86]
 [ 1225    13]]
Accuracy:  0.9006892462758468
F1 Score:  0.011799410029498527
[[12145    90]
 [ 1250     8]]


In [ ]:
process.testRandomForest(train, test)

process.testRandomForest(train_normalized, test_normalized)

process.testRandomForest(train_smoothed, test_smoothed)

process.testRandomForest(train_smoothed_normalized, test_smoothed_normalized)

In [ ]:
normalized_df.head()

In [54]:
process.testRandomForest(train, test)

Accuracy:  0.9105462091454828
F1 Score:  0.0
[[12286     0]
 [ 1207     0]]


In [ ]:
process.testRandomForest(train_normalized, test_normalized)

In [ ]:
process.testKNeighborsClassifier(train, test)

In [ ]:
#process.testLogisticRegression(train_smoothed, test_smoothed)

In [ ]:
#process.testRandomForest(train_smoothed, test_smoothed)

In [ ]:
#process.testKNeighborsClassifier(train_smoothed, test_smoothed)